services:
  - type: web
    name: dantitmuss-magic
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /acaan
        destination: /acaan-trainer.html
